apiVersion: v1
metadata:
  name: amitabh-aws-cluster4
baseDomain: purple-chesterfield.com
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
  platform:
    aws:
      rootVolume:
        iops: 4000
        size: 100
        type: io1
      type: m5.4xlarge
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 3
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 100
        type: io1
      type: m5.4xlarge
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-east-1
pullSecret: "" # skip, hive will inject based on it's secrets
sshKey: |-
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDV3ixDHI2dxRIK0NU0mu+XEuTJ99c9v6ylL+RYCtOPnOXkiauTJTJW92aJrBegYq583Gp2+Rr077YEqY5hsi1Ya49ZrYzIKd+l/iMYI6fBock1WVdKaX7de/ErgN/F1NQWSLwRb2SQxuyve0rYg7JWYPwKzpRMNDv4ZQexMsVQWGqw2VYMmbHcAlVq6VXj9KPU+vYH8NkoyV13SbnQPfuk9OOrbzI/BpkT+8eQoQMaRS1tzMX9gRs2j34hf3jCqf3ArssVWscotk5ugosCI2IgH5wDvWmolFoEVnutu58CNwum/36gu/qFx3g7MWnd2Zqebz8cyq981cYSeX7nbfqmeoMaH0xe+6BJckQP3vDgJn4GXC3I1QrLMdWo9TFfjCx8HINaYELcT1w14f2jVBRc606H32D+R/pICrzrRqIXnscKY5COmydhct41wS4/QIKCCORpwceAzolndYUucZ/ISckEC/ZXL8xnR9gdrGCSKiPFaNmQLBUYNTiEvj3XlPuHhF+BGF6818nzp4NmQBkBOHf1uJIYbb16Y9LFcQr/H1i0Ajl215npdxlKRS3v12MHI3sg2AH1TUs849SVndKmPRfSRX16mCm6x721P2jUeniTZPfVJiSWXN5g7NU/UhApwj233P7HLC8d28Ovtl66/IfFG2jpanbU9lUk88rFgQ== root@suasion1.fyre.ibm.com