# Default values for aws-ocp-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

#spec:
#  baseDomain: purple-chesterfield.com
baseDomain: purple-chesterfield.com
clusterName: amitabh-aws-cluster1

imageSetRef:
  name: img4.3.21-x86-64

platform:
  aws:
    region: us-east-1
    type: m5.4xlarge

replicas: 3

data:
  installconfig: YXBpVmVyc2lvbjogdjEKbWV0YWRhdGE6CiAgbmFtZTogYW1pdGFiaC1hd3MtY2x1c3RlcjQKYmFzZURvbWFpbjogcHVycGxlLWNoZXN0ZXJmaWVsZC5jb20KY29udHJvbFBsYW5lOgogIGh5cGVydGhyZWFkaW5nOiBFbmFibGVkCiAgbmFtZTogbWFzdGVyCiAgcmVwbGljYXM6IDMKICBwbGF0Zm9ybToKICAgIGF3czoKICAgICAgcm9vdFZvbHVtZToKICAgICAgICBpb3BzOiA0MDAwCiAgICAgICAgc2l6ZTogMTAwCiAgICAgICAgdHlwZTogaW8xCiAgICAgIHR5cGU6IG01LjR4bGFyZ2UKY29tcHV0ZToKLSBoeXBlcnRocmVhZGluZzogRW5hYmxlZAogIG5hbWU6IHdvcmtlcgogIHJlcGxpY2FzOiAzCiAgcGxhdGZvcm06CiAgICBhd3M6CiAgICAgIHJvb3RWb2x1bWU6CiAgICAgICAgaW9wczogMjAwMAogICAgICAgIHNpemU6IDEwMAogICAgICAgIHR5cGU6IGlvMQogICAgICB0eXBlOiBtNS40eGxhcmdlCm5ldHdvcmtpbmc6CiAgY2x1c3Rlck5ldHdvcms6CiAgLSBjaWRyOiAxMC4xMjguMC4wLzE0CiAgICBob3N0UHJlZml4OiAyMwogIG1hY2hpbmVDSURSOiAxMC4wLjAuMC8xNgogIG5ldHdvcmtUeXBlOiBPcGVuU2hpZnRTRE4KICBzZXJ2aWNlTmV0d29yazoKICAtIDE3Mi4zMC4wLjAvMTYKcGxhdGZvcm06CiAgYXdzOgogICAgcmVnaW9uOiB1cy1lYXN0LTEKcHVsbFNlY3JldDogIiIgIyBza2lwLCBoaXZlIHdpbGwgaW5qZWN0IGJhc2VkIG9uIGl0J3Mgc2VjcmV0cwpzc2hLZXk6IHwtCiAgICBzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUFEQVFBQkFBQUNBUURWM2l4REhJMmR4UklLME5VMG11K1hFdVRKOTljOXY2eWxMK1JZQ3RPUG5PWGtpYXVUSlRKVzkyYUpyQmVnWXE1ODNHcDIrUnIwNzdZRXFZNWhzaTFZYTQ5WnJZeklLZCtsL2lNWUk2ZkJvY2sxV1ZkS2FYN2RlL0VyZ04vRjFOUVdTTHdSYjJTUXh1eXZlMHJZZzdKV1lQd0t6cFJNTkR2NFpRZXhNc1ZRV0dxdzJWWU1tYkhjQWxWcTZWWGo5S1BVK3ZZSDhOa295VjEzU2JuUVBmdWs5T09yYnpJL0Jwa1QrOGVRb1FNYVJTMXR6TVg5Z1JzMmozNGhmM2pDcWYzQXJzc1ZXc2NvdGs1dWdvc0NJMklnSDV3RHZXbW9sRm9FVm51dHU1OENOd3VtLzM2Z3UvcUZ4M2c3TVduZDJacWViejhjeXE5ODFjWVNlWDduYmZxbWVvTWFIMHhlKzZCSmNrUVAzdkRnSm40R1hDM0kxUXJMTWRXbzlURmZqQ3g4SElOYVlFTGNUMXcxNGYyalZCUmM2MDZIMzJEK1IvcElDcnpyUnFJWG5zY0tZNUNPbXlkaGN0NDF3UzQvUUlLQ0NPUnB3Y2VBem9sbmRZVXVjWi9JU2NrRUMvWlhMOHhuUjlnZHJHQ1NLaVBGYU5tUUxCVVlOVGlFdmozWGxQdUhoRitCR0Y2ODE4bnpwNE5tUUJrQk9IZjF1SklZYmIxNlk5TEZjUXIvSDFpMEFqbDIxNW5wZHhsS1JTM3YxMk1ISTNzZzJBSDFUVXM4NDlTVm5kS21QUmZTUlgxNm1DbTZ4NzIxUDJqVWVuaVRaUGZWSmlTV1hONWc3TlUvVWhBcHdqMjMzUDdITEM4ZDI4T3Z0bDY2L0lmRkcyanBhbmJVOWxVazg4ckZnUT09IHJvb3RAc3Vhc2lvbjEuZnlyZS5pYm0uY29t


stringData:
  aws_access_key_id: <<change-me>>
  aws_secret_access_key: <<change-me>>
  dockerconfigjson: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3p4eGFjbmlibWNvbTF2bmFuNXVtaHppd3hoejJlYmdqdGJubHR0azpZMDA2T1lPWUtXVVhDNDJMRFBSN1NBSFVYTTlQNzc2MFdCQ0VDWDQxVlI1STJXM1BNRUJQR0dUMzJGMTNSMVE2","email":"zxxa@cn.ibm.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3p4eGFjbmlibWNvbTF2bmFuNXVtaHppd3hoejJlYmdqdGJubHR0azpZMDA2T1lPWUtXVVhDNDJMRFBSN1NBSFVYTTlQNzc2MFdCQ0VDWDQxVlI1STJXM1BNRUJQR0dUMzJGMTNSMVE2","email":"zxxa@cn.ibm.com"},"registry.connect.redhat.com":{"auth":"NTI4NjQ4MzR8dWhjLTFWTkFONXVNSFppV3hoWjJFYmdKVGJubHRUSzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmhOV0V5WWpnMU1UQmxNbUUwWkRNMFlUQmxNbVZoTURoaFlUWmtNRGRtTWlKOS5GR1NxcEd4VHZwWThsTVZ6YUNMWVlQVzl0eTJOWXd0eVFxUk1JSmZQc3Q1M0hBQ0Y5T0dzcmdYSFZ1MEwwMWZfN2dOMDFUV21TOHVESTBJNERMSmNBdEVrZkF3MENqd21zcEE0THI3bkFsWEdLemJpYmxvVDNCTXRONV9XVkFWMF95Vl9SMTM5bXBSLUIxZFFFY0tlZVNxaGU0a2VRQlEybnViNU9ab1J0ekJZSHpPZWcwd2hSbEJ1bk50V2MzMGItdlVLXzUtOHNMcGdWWXR6RHo2aFduMTk2RE9DNjJ1S1BKMFJjN2xnTjFLZEh1dldReGtiQWx3aGQxSnI3VUc0bmNmeEhMeU9fVUtRLWtOSFVUMDlUVE5xa1pkaUY3RWxwdmdzZnB5dFVoOXR2ajhUeW1Ia1dmMEhRUndyQ2tnWGtyeW9zRXlsRXR1RGtFNmdVQTZTZFI4UjNNUlRKeUU1S0xZZXlxSlk1SGE2bzBPMTZobGRtemQ0djlxTk5uaERtQjZUSnc2VkxsdUhQMGpKUmgwQllMZmpqQ2YwN0Nhdl9LbXRqUDFZTFVjUHF1LWw5MUNwS09SR05jWFJCdktpbHFkSDhSNmpjS25Id2FxYVgtd2RHMUs3TWYtOWZnTmUzOGV6MXh5RWt3MGwzMTAwVjg2Z0FpdnpiYzV6M3p6VTdXMUNSeGl5LUFtWTQ0N2s2LWlEU0NNYmtqbE1kblVIZi04ZVhSSlROMDZnZExJR0hVakhEZ0JHOWw2d3JlVDZtZHVfUlVuTlFDYk9FeG5rNDJPOERmeG9ISGJXeXp5eUYzcHVQSHM1a0x5WklyUmVkWVlnWWpEa3FZTUpKbnpSU3NmWWJGV2dYR1VDSERjWF9UdS1sempBTVVHWDB4aHNCcmV3ZnBHWEJ0aw==","email":"zxxa@cn.ibm.com"},"registry.redhat.io":{"auth":"NTI4NjQ4MzR8dWhjLTFWTkFONXVNSFppV3hoWjJFYmdKVGJubHRUSzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmhOV0V5WWpnMU1UQmxNbUUwWkRNMFlUQmxNbVZoTURoaFlUWmtNRGRtTWlKOS5GR1NxcEd4VHZwWThsTVZ6YUNMWVlQVzl0eTJOWXd0eVFxUk1JSmZQc3Q1M0hBQ0Y5T0dzcmdYSFZ1MEwwMWZfN2dOMDFUV21TOHVESTBJNERMSmNBdEVrZkF3MENqd21zcEE0THI3bkFsWEdLemJpYmxvVDNCTXRONV9XVkFWMF95Vl9SMTM5bXBSLUIxZFFFY0tlZVNxaGU0a2VRQlEybnViNU9ab1J0ekJZSHpPZWcwd2hSbEJ1bk50V2MzMGItdlVLXzUtOHNMcGdWWXR6RHo2aFduMTk2RE9DNjJ1S1BKMFJjN2xnTjFLZEh1dldReGtiQWx3aGQxSnI3VUc0bmNmeEhMeU9fVUtRLWtOSFVUMDlUVE5xa1pkaUY3RWxwdmdzZnB5dFVoOXR2ajhUeW1Ia1dmMEhRUndyQ2tnWGtyeW9zRXlsRXR1RGtFNmdVQTZTZFI4UjNNUlRKeUU1S0xZZXlxSlk1SGE2bzBPMTZobGRtemQ0djlxTk5uaERtQjZUSnc2VkxsdUhQMGpKUmgwQllMZmpqQ2YwN0Nhdl9LbXRqUDFZTFVjUHF1LWw5MUNwS09SR05jWFJCdktpbHFkSDhSNmpjS25Id2FxYVgtd2RHMUs3TWYtOWZnTmUzOGV6MXh5RWt3MGwzMTAwVjg2Z0FpdnpiYzV6M3p6VTdXMUNSeGl5LUFtWTQ0N2s2LWlEU0NNYmtqbE1kblVIZi04ZVhSSlROMDZnZExJR0hVakhEZ0JHOWw2d3JlVDZtZHVfUlVuTlFDYk9FeG5rNDJPOERmeG9ISGJXeXp5eUYzcHVQSHM1a0x5WklyUmVkWVlnWWpEa3FZTUpKbnpSU3NmWWJGV2dYR1VDSERjWF9UdS1sempBTVVHWDB4aHNCcmV3ZnBHWEJ0aw==","email":"zxxa@cn.ibm.com"}}}'
  sshPrivatekey:
    -----BEGIN RSA PRIVATE KEY-----
    MIIJKgIBAAKCAgEA1d4sQxyNncUSCtDVNJrvlxLkyffXPb+spS/kWArTj5zl5Imr
    kyUyVvdmiawXoGKufNxqdvka9O+2BKmOYbItWGuPWa2MyCnfpf4jGCOnwaHJNVlX
    Sml+3XvxK4DfxdTUFki8EW9kkMbsr3tK2IOyVmD8Cs6UTDQ7+GUHsTLFUFhqsNlW
    DJmx3AJVaulV4/Sj1Pr2B/DZKMldd0m50D37pPTjq28yPwaZE/vHkKEDGkUtbczF
    /YEbNo9+IX94wqn9wK7LFVrHKLZOboKLAiNiIB+cA71pqJRaBFZ7rbufAjcLpv9+
    oLv6hcd4OzFp3dmanm8/HMqvfNXGEnl+5236pnqDGh9MXvugSXJED97w4CZ+Blwt
    yNUKyzHVqPUxX4wsfByDWmBC3E9cNeH9o1QUXOtOh99g/kf6SAq860aiF57HCmOQ
    jpsnYXLeNcEuP0CCggjkacHHgM6JZ3WFLnGfyEnJBAv2Vy/MZ0fYHaxgkiojxWjZ
    kCwVGDU4hL4915T7h4RfgRhevNfJ86eDZkAZATh39biSGG29emPSxXEK/x9YtAI5
    dteZ6XcZSkUt79djByN7INgB9U1LPOPUlZ3Spj0X0kV9epgpuse9tT9o1Hp4k2T3
    1SYkllzeYOzVP1IQKcI9t9z+xywvHdvDr7ZeuvyHxRto6Wp21PZVJPPKxYECAwEA
    AQKCAgEAgx+NebQm64UpE7KIFZGsta5i0aV/tR8whbLASG6S2Wkz1hPGOxhCLenP
    VzdI4Q+/tVQafkkqiuPxcBhY8HMitCR2JmBugUaTFZ2j/KfXsbM0vt3A1CGsI7Va
    3vZLvGpJgkQj8nieatlbwhdQg0DzdVxPC30ulS4tWpTuy2i6axFakIUf6efNkXto
    zXy0KWgTjoAzmhjDu+sBwCJWp2NpRvDSKYiqgNPVxNfIulbNpSymtrwm489lVOVT
    SsxxyMAakSlZ4AThOIfVvJGTEsOI5PMcX3qhLjeOnTw85f6zddMz9LaO95No/N6Y
    S4p3Qwqobtz8D/YA9APJRghxkwjt9EYLt2VDQOUbbs9qNzXo1bgOsl3cx9PGW+G5
    SBynLoBMXU/3e/F5g7qm5r66fK+xle5PHGBNi3lNTONeMpQ3AP8oF0z1bHKTQDJG
    e7j5IOAxrP1MVatIN68i6eo9YhaFpwk+6LZyxSl1s76XAqNW9QNV8y6hnH3C6N4d
    DN7JJAzm2x3PfDdewW8qfL6Gz1cdSVsG7FwOHtqsTNaPHzohKx3uuqKMx4Bup1Q1
    TxROwwEyaheWhaywryZ1djFFqvmWjc2LuuCjsacRlw5vWRK0w1euX33HOLioGTYQ
    W4chuFZfU0L7i4Ai1oZIhWRaaSQ+tBHASnF3VV+FNkXBAOcb5nECggEBAP750D3u
    48cG26wllzZUqHdLDUgRQzMo1w0h4gkKGBGXpUIqw1DuR/SajmawuVc70cD7I0xV
    9qRWtIbBKoV5lNFCxb6RadH6OPqXeFwpb2WmObp8ZbZ5tYGL3zPKM3M/Rk3YpaYa
    LVsiNhaXDVGgzbxwS9Raqf7ZqQ+TkZPVMFJUavBJxOe6FjiayMLQQF3x9yu+2lBg
    SWmQyrrip7MQ7fEAzSSMini5xvCaph1kGO8mlVKUGJ+DIyFRGqXaIs35X4XoAP8J
    Qw4ShNA/noNKs8P2fSV/OkgjQk4e/IvvD6gT3ZjL7rzQ+mGJbHzSABKYW7Y8NcED
    CmseazbuRGwOIr0CggEBANa6FsVcF2LTkpgHohBnFZYoY0NnVzO8lSRvAfbrOTx4
    P3jHfLwGQERJppRMqBIFm/rCIdcRjireVhl+wDxfeuUo1sRZ11GcTfrcpAcvZdYq
    89Zj+GZs0mvkoiXxnhVfR+r98islh6hQ4ttkNlFsnWp9gF428t8/GZak2RiLQZhn
    KF+ldlF8mln35fHIW8PPGfM8kt3ZELEPyIVn/Bgm3713YM7vswDUZpOkBoJ2xSnp
    8UVyRboDO+nG13jEGC4tSlVxed+GKaU5U991OShtupfNCUgZeUxcg20dIJryAHC3
    nLxyngBTx9powtQknTQqbEtbohlBDzpnAsBk3bAeXBUCggEAFxkobUPj7JbJdbne
    DfTzYgMxi9LMhKjxemYUZP8+GPHk7a6UDRPY/ua1ecYOtEFeCh52Hyc2dcLJDeAX
    6wmNmrty0IW50WTanpD0PV0fk1TQq/0y9anm8HpsWPO7X3he9RRoRTjf3P6nabp7
    YWaw3J5LsEwaVFUBhMC4kmzguMSe/2+fX+KyuqQDBer5ucj+vD7I5jkizWZphy6b
    RJSHCasp6mK09KTXydoorEbyH1AefOGfrWui1hTT1iyBtKkfpzDSTkhXg8HXuEnb
    IUe2K018HtZ8wCY5jnwuIrsgbviFvZ7T3NUNqaJaaqBXk1esD0E7GWYeHoAd9Fb3
    adaJ/QKCAQEAx4zu5oD79srafFDzqryyEfb8sMJUBu+lxtMnBzp42ZqCmhMB95bz
    mMK9fSp0MzNlTrelTUKyVWKEr3Lc4f51rouyc41ujhhtW8o64baJtGv8aWxEh6Nw
    NfanPg36NLB0nI1dxf09wg1RlkPeOvNuo214o5X7Rb9VX2tZmfaogiK0IZcaiwX6
    R8watQTXSvSnkCXl8yfr3DDn0Brf6+4Mlf5gSE/4kbfSkDiqGAqalqYjo79bz098
    GXjB/Ch4tElAwIERmsoK39KUAKHm+YxoEPTqQEf0MyPyu6+LApQOFrJ8haEa9wDl
    RTOAhDh2o+kc9Td2QHP22/apVvUmFKtSNQKCAQEAkp5LDXU1XLaSIWOkWBzv18/J
    jUzTrRDq5ANhgHDVbrISLKOMmhs1yMIuNz08wHk6bjehXI9tY7N+OAP9ZZ1SwuK0
    pRas+R1naN7sviaLfSFcZonLP5vMnHy/LjE4/xboNnfXdqSxKxTPS4qYEkMqjI22
    VOsuyg4uaI4AMNLJCdXV3d7Y5e5VziCj0vilu2fcTX7C7B2oC62t83VJ+qU5DZcw
    NnZkM6C2QuQ5AXeQIUhe9XQXPu1blcPO6mFZuJAAVD3hTm4MHZoNmcyYGkJbenOl
    XZ1Z2JErlJ5VFqmact8A16f9M//9rZGEHBAmmykThAQMdNQAO/YWFx78VVyMHQ==
    -----END RSA PRIVATE KEY-----